package main

import (
  "bytes"; "context"; "crypto/sha1"; "encoding/hex"; "encoding/json"; "flag"; "fmt"; "io"; "log"; "net/http"; "os"; "strings"; "time"
)

type Config struct{ Server struct{Addr string `json:"addr"`} `json:"server"`; Sandbox SandboxConfig `json:"sandbox"` }
type SandboxConfig struct{ Namespace, ServiceAccount, APIServer, TokenFile, Image, ImagePullPolicy, WorkspaceMountPath, StorageClass, WorkspaceSize, DefaultCPU, DefaultMemory string; ToolPort, BrowserPort, WebPort int; CreateNamespace, NetworkPolicyEnabled bool; DefaultNetworkMode string }
type EnsureRequest struct{ SandboxID, SessionID, RunID, RuntimeID, OrgID, ProjectID, AgentID, SnapshotID, Image, WorkspaceSize, StorageClass string; Services []map[string]any; Network struct{Mode string `json:"mode"`} `json:"network"`; Limits struct{CPU, Memory string} `json:"limits"` }
type Status struct{ SandboxID, Phase, Namespace, PodName, PodIP, ServiceName, WorkspacePVC, Image string; Endpoints map[string]string `json:"endpoints"` }
type App struct{ cfg Config; kube *Kube }

func main(){ cfgPath:=flag.String("config","","config json"); flag.Parse(); cfg:=defaults(); if *cfgPath!=""{must(readJSON(*cfgPath,&cfg))}; app:=&App{cfg:cfg,kube:NewKube(cfg.Sandbox)}; mux:=http.NewServeMux(); mux.HandleFunc("/healthz",func(w http.ResponseWriter,r *http.Request){out(w,map[string]any{"ok":true})}); mux.HandleFunc("/readyz",func(w http.ResponseWriter,r *http.Request){out(w,map[string]any{"ok":true})}); mux.HandleFunc("/v1/sandboxes/ensure",app.ensure); mux.HandleFunc("/v1/sandboxes/",app.byID); mux.HandleFunc("/v1/sandboxes",app.list); addr:=cfg.Server.Addr; if addr==""{addr=":18082"}; log.Printf("listen %s",addr); must(http.ListenAndServe(addr,cors(mux))) }
func defaults() Config{ var c Config; c.Server.Addr=":18082"; c.Sandbox.Namespace="aisphere-sandbox"; c.Sandbox.ServiceAccount="agentkit-sandbox-controller"; c.Sandbox.CreateNamespace=true; c.Sandbox.NetworkPolicyEnabled=true; c.Sandbox.DefaultNetworkMode="offline"; c.Sandbox.Image="registry.local/aisphere/agentkit-sandbox:latest"; c.Sandbox.ImagePullPolicy="IfNotPresent"; c.Sandbox.WorkspaceMountPath="/workspace"; c.Sandbox.StorageClass="nfs-client"; c.Sandbox.WorkspaceSize="10Gi"; c.Sandbox.ToolPort=18081; c.Sandbox.BrowserPort=9222; c.Sandbox.WebPort=6080; c.Sandbox.DefaultCPU="500m"; c.Sandbox.DefaultMemory="1Gi"; return c }
func (a *App) list(w http.ResponseWriter,r *http.Request){ out(w,map[string]any{"items":[]any{}}) }
func (a *App) ensure(w http.ResponseWriter,r *http.Request){ if r.Method!="POST"{method(w);return}; var req EnsureRequest; if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil{http.Error(w,err.Error(),400);return}; if req.SandboxID==""{req.SandboxID=id(req.SessionID,req.RunID)}; st,err:=a.kube.Ensure(r.Context(),req); reply(w,st,err) }
func (a *App) byID(w http.ResponseWriter,r *http.Request){ parts:=strings.Split(strings.Trim(strings.TrimPrefix(r.URL.Path,"/v1/sandboxes/"),"/"),"/"); if len(parts)==0||parts[0]==""{http.NotFound(w,r);return}; sid:=parts[0]; if len(parts)==1{ if r.Method=="GET"{st,err:=a.kube.Get(r.Context(),sid); reply(w,st,err);return}; if r.Method=="DELETE"{reply(w,map[string]any{"ok":true},a.kube.Delete(r.Context(),sid,r.URL.Query().Get("deleteWorkspace")=="true"));return}; method(w);return}; switch parts[1]{case "restart": st,err:=a.kube.Restart(r.Context(),sid); reply(w,st,err); case "logs": s,err:=a.kube.Logs(r.Context(),sid,r.URL.Query().Get("tail")); if err!=nil{http.Error(w,err.Error(),500);return}; w.Header().Set("Content-Type","text/plain"); _,_=w.Write([]byte(s)); case "tools": a.proxy(w,r,sid,parts); default: http.NotFound(w,r)} }
func (a *App) proxy(w http.ResponseWriter,r *http.Request,sid string,parts []string){ st,err:=a.kube.Get(r.Context(),sid); if err!=nil{http.Error(w,err.Error(),500);return}; target:=st.Endpoints["tools"]+"/v1/tools"; method:="GET"; var body io.Reader; if len(parts)>2&&parts[2]=="call"{target=st.Endpoints["tools"]+"/v1/tools/call"; method="POST"; body=r.Body}; req,_:=http.NewRequestWithContext(r.Context(),method,target,body); req.Header.Set("Content-Type","application/json"); resp,err:=http.DefaultClient.Do(req); if err!=nil{http.Error(w,err.Error(),502);return}; defer resp.Body.Close(); w.WriteHeader(resp.StatusCode); _,_=io.Copy(w,resp.Body) }

type Kube struct{ c SandboxConfig; api, token string; client *http.Client }
func NewKube(c SandboxConfig)*Kube{ api:=c.APIServer; if api==""{api="https://kubernetes.default.svc"}; f:=c.TokenFile; if f==""{f="/var/run/secrets/kubernetes.io/serviceaccount/token"}; b,_:=os.ReadFile(f); return &Kube{c:c,api:strings.TrimRight(api,"/"),token:strings.TrimSpace(string(b)),client:&http.Client{Timeout:30*time.Second}} }
func (k *Kube) req(ctx context.Context,m,u string,in,outv any)error{ var body io.Reader; if in!=nil{b,_:=json.Marshal(in); body=bytes.NewReader(b)}; r,_:=http.NewRequestWithContext(ctx,m,k.api+u,body); r.Header.Set("Content-Type","application/json"); if k.token!=""{r.Header.Set("Authorization","Bearer "+k.token)}; resp,err:=k.client.Do(r); if err!=nil{return err}; defer resp.Body.Close(); data,_:=io.ReadAll(resp.Body); if resp.StatusCode>=300{return fmt.Errorf("k8s %s %s: %s",m,u,string(data))}; if outv!=nil{return json.Unmarshal(data,outv)}; return nil }
func (k *Kube) Ensure(ctx context.Context,r EnsureRequest)(*Status,error){ ns:=k.c.Namespace; if k.c.CreateNamespace{_=k.req(ctx,"POST","/api/v1/namespaces",map[string]any{"apiVersion":"v1","kind":"Namespace","metadata":map[string]any{"name":ns}},nil)}; sid:=r.SandboxID; pod:="aisb-"+sid; pvc:="aisb-ws-"+sid; img:=first(r.Image,k.c.Image); _=k.req(ctx,"POST","/api/v1/namespaces/"+ns+"/persistentvolumeclaims",pvcObj(pvc,first(r.StorageClass,k.c.StorageClass),first(r.WorkspaceSize,k.c.WorkspaceSize),sid),nil); _=k.req(ctx,"POST","/api/v1/namespaces/"+ns+"/configmaps",cmObj(pod,sid,r.Services),nil); _=k.req(ctx,"POST","/api/v1/namespaces/"+ns+"/services",svcObj(pod,sid,k.c),nil); _=k.req(ctx,"POST","/api/v1/namespaces/"+ns+"/pods",podObj(pod,sid,pvc,img,k.c,r),nil); return k.Get(ctx,sid) }
func (k *Kube) Get(ctx context.Context,sid string)(*Status,error){ ns:=k.c.Namespace; pod:="aisb-"+sid; var obj map[string]any; err:=k.req(ctx,"GET","/api/v1/namespaces/"+ns+"/pods/"+pod,nil,&obj); st:=&Status{SandboxID:sid,Namespace:ns,PodName:pod,ServiceName:pod,WorkspacePVC:"aisb-ws-"+sid,Phase:"unknown",Image:k.c.Image,Endpoints:map[string]string{"tools":fmt.Sprintf("http://%s.%s.svc:%d",pod,ns,k.c.ToolPort),"browser":fmt.Sprintf("http://%s.%s.svc:%d",pod,ns,k.c.BrowserPort),"web":fmt.Sprintf("http://%s.%s.svc:%d",pod,ns,k.c.WebPort)}}; if err!=nil{return st,err}; if s,ok:=obj["status"].(map[string]any);ok{ if p,ok:=s["phase"].(string);ok{st.Phase=strings.ToLower(p)}; if ip,ok:=s["podIP"].(string);ok{st.PodIP=ip} }; return st,nil }
func (k *Kube) Restart(ctx context.Context,sid string)(*Status,error){_=k.req(ctx,"DELETE","/api/v1/namespaces/"+k.c.Namespace+"/pods/aisb-"+sid,nil,nil); return k.Get(ctx,sid)}
func (k *Kube) Delete(ctx context.Context,sid string,del bool)error{ns:=k.c.Namespace; for _,u:=range []string{"/api/v1/namespaces/"+ns+"/pods/aisb-"+sid,"/api/v1/namespaces/"+ns+"/services/aisb-"+sid,"/api/v1/namespaces/"+ns+"/configmaps/aisb-"+sid}{_=k.req(ctx,"DELETE",u,nil,nil)}; if del{_=k.req(ctx,"DELETE","/api/v1/namespaces/"+ns+"/persistentvolumeclaims/aisb-ws-"+sid,nil,nil)}; return nil}
func (k *Kube) Logs(ctx context.Context,sid,tail string)(string,error){ if tail==""{tail="200"}; req,_:=http.NewRequestWithContext(ctx,"GET",fmt.Sprintf("%s/api/v1/namespaces/%s/pods/aisb-%s/log?tailLines=%s",k.api,k.c.Namespace,sid,tail),nil); if k.token!=""{req.Header.Set("Authorization","Bearer "+k.token)}; resp,err:=k.client.Do(req); if err!=nil{return "",err}; defer resp.Body.Close(); b,_:=io.ReadAll(resp.Body); return string(b),nil }
func labels(id string)map[string]any{return map[string]any{"app.kubernetes.io/name":"aisphere-sandbox","aisphere.io/sandbox-id":id}}
func pvcObj(n,sc,size,id string)map[string]any{spec:=map[string]any{"accessModes":[]string{"ReadWriteOnce"},"resources":map[string]any{"requests":map[string]any{"storage":size}}}; if sc!=""{spec["storageClassName"]=sc}; return map[string]any{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":map[string]any{"name":n,"labels":labels(id)},"spec":spec}}
func cmObj(n,id string,svc []map[string]any)map[string]any{b,_:=json.MarshalIndent(svc,"","  "); return map[string]any{"apiVersion":"v1","kind":"ConfigMap","metadata":map[string]any{"name":n,"labels":labels(id)},"data":map[string]any{"tool-manifest.json":string(b)}}}
func svcObj(n,id string,c SandboxConfig)map[string]any{return map[string]any{"apiVersion":"v1","kind":"Service","metadata":map[string]any{"name":n,"labels":labels(id)},"spec":map[string]any{"selector":labels(id),"ports":[]map[string]any{{"name":"tools","port":c.ToolPort,"targetPort":c.ToolPort},{"name":"browser","port":c.BrowserPort,"targetPort":c.BrowserPort},{"name":"web","port":c.WebPort,"targetPort":c.WebPort}}}}}
func podObj(n,id,pvc,img string,c SandboxConfig,r EnsureRequest)map[string]any{return map[string]any{"apiVersion":"v1","kind":"Pod","metadata":map[string]any{"name":n,"labels":labels(id)},"spec":map[string]any{"serviceAccountName":c.ServiceAccount,"securityContext":map[string]any{"runAsNonRoot":true,"runAsUser":1000,"runAsGroup":1000,"fsGroup":1000},"containers":[]map[string]any{{"name":"sandbox","image":img,"imagePullPolicy":c.ImagePullPolicy,"ports":[]map[string]any{{"containerPort":c.ToolPort},{"containerPort":c.BrowserPort},{"containerPort":c.WebPort}},"env":[]map[string]any{{"name":"AISPHERE_WORKSPACE","value":c.WorkspaceMountPath},{"name":"AISPHERE_TOOL_PORT","value":fmt.Sprint(c.ToolPort)}},"resources":map[string]any{"requests":map[string]any{"cpu":first(r.Limits.CPU,c.DefaultCPU),"memory":first(r.Limits.Memory,c.DefaultMemory)},"limits":map[string]any{"cpu":first(r.Limits.CPU,c.DefaultCPU),"memory":first(r.Limits.Memory,c.DefaultMemory)}},"volumeMounts":[]map[string]any{{"name":"workspace","mountPath":c.WorkspaceMountPath},{"name":"manifest","mountPath":"/etc/aisphere/sandbox","readOnly":true}}}},"volumes":[]map[string]any{{"name":"workspace","persistentVolumeClaim":map[string]any{"claimName":pvc}},{"name":"manifest","configMap":map[string]any{"name":n}}}}}}
func first(a,b string)string{if a!=""{return a};return b}; func readJSON(p string,v any)error{b,e:=os.ReadFile(p);if e!=nil{return e};return json.Unmarshal(b,v)}; func must(e error){if e!=nil{log.Fatal(e)}}; func out(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");_=json.NewEncoder(w).Encode(v)}; func reply(w http.ResponseWriter,v any,e error){if e!=nil{http.Error(w,e.Error(),500);return};out(w,v)}; func method(w http.ResponseWriter){http.Error(w,"method not allowed",405)}; func cors(h http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if r.Method=="OPTIONS"{return};h.ServeHTTP(w,r)})}; func id(s,run string)string{h:=sha1.Sum([]byte(s+"-"+run));return "sbx-"+hex.EncodeToString(h[:])[:12]}
